title: Intelligent Systems and Operations in Aviation 
description: Research Group at the ZHAW Institute for Data Analysis and Process Design, led by Dr. Manuel Renold
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
